<?php

function file_check_cron() {
  $interval = variable_get('file_check_interval', 8 * 60 * 60);
  $email_interval = variable_get('file_check_email_interval', 24 * 60 * 60);

  /*variable_set('file_check_next_execution', 0);
  variable_set('file_check_next_email', 0);*/

  if (time() >= variable_get('file_check_next_execution', 0)) {

    $result = db_select('file_check', 'c')
    ->fields('c')
    ->execute();

    foreach ($result as $record) {
      _file_check_check($record->path, $record->text);
    }

    variable_set('file_check_next_execution', time() + $interval);
  }
}

function file_check_mail($key, &$message, $params) {
  switch ($key) {
    case 'admin_alert':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

function _file_check_check($file_path, $required_text) {

  $file_text = file_get_contents(DRUPAL_ROOT . '/' . $file_path);

  if (strpos($file_text, $required_text) === FALSE) {
    watchdog('file_check', 'File modification check did not find the expected text in ' . $file_path);

    if (time() >= variable_get('file_check_next_email', 0)) {

      $message = "The required text:\n\n--------------------\n\n" . $required_text . "\n\n--------------------\n\nWas not found in the " . $file_path . " file:\n\n--------------------\n\n" . $file_text . "\n\n--------------------\n";

      $params = array(
        'subject' => variable_get('site_name') . ' - File modification check failed',
        'body' => $message,
      );
      drupal_mail('file_check', 'admin_alert', variable_get('site_mail', ''), language_default(), $params);

      variable_set('file_check_next_email', time() + $email_interval);

    }
  }

}